import Head from "next/head";
import Layout from '../components/Layout';
import Hero from '../components/Hero';
import css from '../styles/Home.module.css';
import Services from "../components/Services";
import Menu from '../components/Menu';
import { client } from "../lib/client";

export default function Home({products}) {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>WE Shop</title>
          <meta name="description" content="Generated by create next app" />
          {/*<link rel="icon" href="/Logo.png" />*/}
        </Head>
        {/* body */}
        <main>
          <Hero/>  
          <Services/>   
          <Menu products={products}/> 
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async() => {
  const query = '*[_type == "products"]';
  const products = await client.fetch(query);
  return{
    props: {products}
  }
}